### ISSUE TITLE
npm install 실패

### ISSUE THREAD

**Issue by sunghyunl22** [teamdable/vv-ts-module-public#1]
![image](https://user-images.githubusercontent.com/39397181/168736987-f0eca686-4eda-4d14-8592-2df6bb2ca328.png)
![image](https://user-images.githubusercontent.com/39397181/168737035-cd1bd32e-f714-4d39-b94f-2e2c40703ee8.png)

```
33 http fetch GET 401 https://npm.pkg.github.com/@teamdable%2fvv-schedule-parser 446ms (cache skip)
34 silly placeDep ROOT @teamdable/vv-schedule-parser@ OK for: test@1.0.0 want: 0.1.6
35 timing idealTree:#root Completed in 452ms
36 timing idealTree:node_modules/@teamdable/vv-schedule-parser Completed in 0ms
37 timing idealTree:buildDeps Completed in 452ms
38 timing idealTree:fixDepFlags Completed in 0ms
39 timing idealTree Completed in 479ms
40 timing command:install Completed in 486ms
41 verbose stack HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="GitHub Package Registry"
41 verbose stack     at /Users/sunghyun/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:84:17
41 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
41 verbose stack     at async Arborist.[nodeFromEdge] (/Users/sunghyun/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:19)
41 verbose stack     at async Arborist.[buildDepStep] (/Users/sunghyun/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
41 verbose stack     at async Arborist.buildIdealTree (/Users/sunghyun/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
41 verbose stack     at async Promise.all (index 1)
41 verbose stack     at async Arborist.reify (/Users/sunghyun/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:149:5)
41 verbose stack     at async Install.install (/Users/sunghyun/.nvm/versions/node/v16.13.0/lib/node_modules/npm/lib/install.js:170:5)
42 verbose statusCode 401
43 verbose pkgid @teamdable/vv-schedule-parser@0.1.6
44 verbose cwd /Users/sunghyun/vv/test
45 verbose Darwin 21.4.0
46 verbose argv "/Users/sunghyun/.nvm/versions/node/v16.13.0/bin/node" "/Users/sunghyun/.nvm/versions/node/v16.13.0/bin/npm" "install" "@teamdable/vv-schedule-parser@0.1.6"
47 verbose node v16.13.0
48 verbose npm  v8.1.0
49 error code E401
50 error Incorrect or missing password.
51 error If you were trying to login, change your password, create an
51 error authentication token or enable two-factor authentication then
51 error that means you likely typed your password in incorrectly.
51 error Please try again, or recover your password at:
51 error     https://www.npmjs.com/forgot
51 error
51 error If you were doing some other operation then your saved credentials are
51 error probably out of date. To correct this please try logging in again with:
51 error     npm login
52 verbose exit 1
```

https://npm.pkg.github.com/@teamdable%2fvv-schedule-parser 이 password를 요구합니다. 
찾아보니 github package registry 를 사용한 install / publish 는 그 저장소가 public이라도 반드시 access token 이 필요하다고 하네요. 
https://stackoverflow.com/a/67273013
(제가 드렸던 데이블의 npm 패키지 저장소는 private이었기 때문에 token 이 이미 있는 상황이었습니다 ㅠㅠ )

github token 없이 설치하려면 npm registry 에 직접 등록하거나, 
vv팀 vpc 안에 [private npm registry](https://verdaccio.org/docs/cli-registry)를 만드는 아이디어가 있는데요, private registry는 사용해보지 않아서 과정에 시행착오가 있을것 같습니다

**Comment by sunghyunl22** [comment]
5/18스크럼 - attention.me 이메일 생기면 npm , 안 생기면 npm registry instance 정도로 방향 잡아놓고 pending
